# Generated by Django 6.0.4 on 2026-04-26 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='categories_name_98d7d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=20)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.category')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gen_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feb_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mar_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apr_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mag_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('giu_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lug_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ago_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('set_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ott_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nov_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dic_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.transaction')),
            ],
            options={
                'db_table': 'budget',
                'ordering': ['transaction', 'year'],
            },
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.transaction')),
            ],
            options={
                'db_table': 'transaction_entries',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['name'], name='transaction_name_137b73_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='transaction_type_840495_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='transaction_categor_bf503b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'type'], name='transaction_categor_08ff0d_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['transaction'], name='budget_transac_09c189_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['year'], name='budget_year_c481a5_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['transaction', 'year'], name='budget_transac_0b1fa1_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('transaction', 'year'), name='unique_budget_transaction_year'),
        ),
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['transaction'], name='transaction_transac_f606c8_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['entry_date'], name='transaction_entry_d_50ea10_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['transaction', 'entry_date'], name='transaction_transac_cfeeae_idx'),
        ),
    ]
