# Generated by Django 6.0.3 on 2026-04-30 23:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=20)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.category')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.transaction')),
            ],
            options={
                'db_table': 'transaction_entries',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.IntegerField()),
                ('gen_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feb_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mar_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apr_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mag_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('giu_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lug_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ago_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('set_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ott_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nov_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dic_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.transaction')),
            ],
            options={
                'db_table': 'budget',
                'constraints': [models.UniqueConstraint(fields=('transaction', 'year'), name='unique_budget_transaction_year')],
            },
        ),
    ]
