# Generated by Django 6.0.4 on 2026-05-03 23:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='categories_name_98d7d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=20)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.category')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('gen_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feb_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mar_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apr_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mag_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('giu_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lug_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ago_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('set_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ott_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nov_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dic_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.transaction')),
            ],
            options={
                'db_table': 'transaction_budgets',
                'ordering': ['transaction', 'year'],
            },
        ),
        migrations.CreateModel(
            name='TransactionMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('movement_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.transaction')),
            ],
            options={
                'db_table': 'transaction_movements',
                'ordering': ['-movement_date', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['name'], name='transaction_name_137b73_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='transaction_type_840495_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='transaction_categor_bf503b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'type'], name='transaction_categor_08ff0d_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionbudget',
            index=models.Index(fields=['transaction'], name='transaction_transac_8f2894_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionbudget',
            index=models.Index(fields=['year'], name='transaction_year_726fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionbudget',
            index=models.Index(fields=['transaction', 'year'], name='transaction_transac_d66d1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionbudget',
            constraint=models.UniqueConstraint(fields=('transaction', 'year'), name='unique_transaction_budget_year'),
        ),
        migrations.AddIndex(
            model_name='transactionmovement',
            index=models.Index(fields=['transaction'], name='transaction_transac_8c4608_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmovement',
            index=models.Index(fields=['movement_date'], name='transaction_movemen_83ed0c_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmovement',
            index=models.Index(fields=['transaction', 'movement_date'], name='transaction_transac_a41d06_idx'),
        ),
    ]
