# Generated by Django 6.0.3 on 2026-05-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Mixed', 'Mixed')], default='Mixed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type'], name='categories_type_735b1a_idx'),
        ),
    ]
